import { ConnectButton } from "@rainbow-me/rainbowkit"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import { Button } from "@/components/ui/button"

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gas Reimbursement Platform</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

    </div>
  )
}

export default Home
